import numpy as np
import matplotlib.pyplot as plt
import json
import os
from PIL import Image
from dotenv import load_dotenv

load_dotenv()

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

curl -O https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/hpTjb6liKBLVHQK0UgMi5A/Recipes.json
curl -O https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/fQUs9wQ6aB6ts6fmkD2V2w/Synthetic-User-Reviews.json
curl -O https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/5_Rr6ohviItzucyWk6nkrw/synthetic-recipe-images.zip

import zipfile

with zipfile.ZipFile("synthetic-recipe-images.zip", 'r') as zip_ref:
    zip_ref.extractall()

Step 1.1: Load JSON
with open("Recipes.json", "r", encoding="utf-8") as f:
    recipe_data = json.load(f)

# Step 1.2: Print key-value pairs
recipe1 = recipe_data[0]

for key, value in recipe1.items():
    print(f"{key} ({type(value).__name__}): {value}")

# Step 1.3: Show image
img_path = f"synthetic_recipe_images/recipe{recipe1['id']}.png"

if os.path.exists(img_path):
    img = Image.open(img_path)
    plt.imshow(img)
    plt.axis("off")
    plt.title(recipe1["name"])
    # plt.show()
else:
    print("Image not found:", img_path)

import os
import base64
from openai import OpenAI

def vision_llm(system_msg, prompt_txt, image_path):

    client = OpenAI(
        api_key=os.getenv("NVIDIA_API_KEY2"),
        base_url="https://integrate.api.nvidia.com/v1"
    )

    # ---------------------------
    # Encode image correctly
    # ---------------------------
    with open(image_path, "rb") as img_file:
        image_base64 = base64.b64encode(img_file.read()).decode("utf-8")

    # detect extension properly
    ext = os.path.splitext(image_path)[1].replace(".", "")

    # ---------------------------
    # Messages
    # ---------------------------
    messages = [
        {"role": "system", "content": system_msg},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": prompt_txt},
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:image/{ext};base64,{image_base64}"
                    }
                }
            ]
        }
    ]

    response = client.chat.completions.create(
        model="meta/llama-3.2-90b-vision-instruct",
        messages=messages,
        max_tokens=300,
        temperature=0.5
    )

    return response.choices[0].message.content

### Define the food image caption prompts
def image_caption_prompt_template(food_name):
    # system message → defines behavior
    image_caption_system_msg = f"""
You are a food image captioning assistant.

Your task:
- Describe the food shown in the image
- Focus specifically on the dish: "{food_name}"
- Keep the description clear and concise
- Mention visible ingredients, textures, and presentation
- Do NOT add unrelated details
"""

    # user prompt → actual instruction
    image_caption_prompt_txt = f"""
Describe the dish "{food_name}" shown in this image.

Include:
- Key ingredients you can see
- Appearance (color, texture)
- Presentation style

Keep it under 3-4 sentences.
"""

    return image_caption_system_msg, image_caption_prompt_txt


# ---------------------------
# Step 3.2: Get prompts
# ---------------------------
recipe1 = recipe_data[0]

system_msg, prompt_txt = image_caption_prompt_template(recipe1["name"])

img_path = f"synthetic_recipe_images/recipe{recipe1['id']}.png"

response = vision_llm(system_msg, prompt_txt, img_path)

print(response)

for i in range(len(recipe_data)):
    
    if (i + 1) % 5 == 0:
        print(f'{i+1} out of {len(recipe_data)} is done')

    # ---------------------------
    # Step 4.1: Get caption prompts
    # ---------------------------
    food_name = recipe_data[i]["name"]
    system_msg, prompt_txt = image_caption_prompt_template(food_name)

    # image path (handles png/jpg safely)
    img_path = None
    for ext in ["png", "jpg", "jpeg"]:
        temp_path = f"synthetic_recipe_images/recipe{recipe_data[i]['id']}.{ext}"
        if os.path.exists(temp_path):
            img_path = temp_path
            break

    # skip if image not found
    if img_path is None:
        print(f"Image not found for recipe {i}")
        recipe_data[i]["image_description"] = None
        continue

    # ---------------------------
    # Step 4.2: Get response
    # ---------------------------
    response = vision_llm(system_msg, prompt_txt, img_path)

    # ---------------------------
    # Save response
    # ---------------------------
    recipe_data[i]["image_description"] = response

print("ALL DONE!")

filename = 'augmented_food_recipe.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(recipe_data, f, indent=4)

import json

### Step 1.1: Load the review dataset
with open("Synthetic-User-Reviews.json", "r", encoding="utf-8") as f:
    user_review_data = json.load(f)

### Step 1.2: Print the first review by key-value pairs
first_review = user_review_data[0]

for key, value in first_review.items():
    print(f"{key} ({type(value).__name__}): {value}")

import ast
import requests
import matplotlib.pyplot as plt
from PIL import Image

### Step 2.1: Get first review
first_review = user_review_data[0]

### Step 2.2: Convert string list → Python list
image_list = ast.literal_eval(first_review["images"])

### Step 2.3: Get first image URL
image_url = image_list[0]

### Step 2.4: Download image using requests
response = requests.get(image_url)

### Step 2.5: Save to temporary file
temp_file = "review_image_placeholder.jpg"

with open(temp_file, "wb") as f:
    f.write(response.content)

### Step 2.6: Open and display image
img = Image.open(temp_file)

plt.imshow(img)
plt.axis("off")
plt.title("User Review Image")
plt.show()

### Prompt template: caption images using review context
def review_context_image_caption_prompt_template(reviews):
    # reviews: text review from user

    ### Step 2.1: System prompt
    review_context_image_caption_system_msg = """
You are a multimodal food review analyst.

Your task:
- Look at the food image AND the user review text
- Generate a caption that combines both visual information and user sentiment
- Be accurate and only describe what is visible in the image
- Use the review to understand taste, quality, and experience
- Do NOT hallucinate ingredients not visible
"""

    ### Step 2.2: User prompt
    review_context_image_caption_prompt_txt = f"""
Generate a detailed caption for the food image.

User review:
{reviews}

Instructions:
- Describe the dish in the image
- Incorporate user sentiment (positive/negative feedback)
- Mention appearance, texture, and presentation
- Keep it 3–5 sentences
"""

    return review_context_image_caption_system_msg, review_context_image_caption_prompt_txt
print(user_review_data[0].keys())

import ast
import os
import requests
from tenacity import retry, stop_after_attempt, wait_exponential

### URL Request function with Retry
@retry(stop=stop_after_attempt(10), wait=wait_exponential(multiplier=1, min=1, max=10))
def get_data_with_retry(url):
    response = requests.get(url, timeout=5)
    response.raise_for_status()
    return response


### Start loop over user reviews
for i in range(len(user_review_data)):

    ### Step 3.1: Convert string → Python list
    review_images = ast.literal_eval(user_review_data[i]["images"])

    review_image_captions = []

    if len(review_images) > 0:

        for img_url in review_images:
            try:
                ### Step 3.2: Fetch image with retry
                image_data = get_data_with_retry(img_url)
                print("Success!")

            except Exception as e:
                print(f"All retries failed at url {img_url}:", e)
                continue

            # Save image temporarily
            image = image_data.content
            with open("review_image_placeholder.jpg", "wb") as img_file:
                img_file.write(image)

            ### Step 3.3: Generate caption using vision LLM
            system_msg, prompt_txt = review_context_image_caption_prompt_template(
                user_review_data[i]["text"]
            )

            caption = vision_llm(
                system_msg,
                prompt_txt,
                "review_image_placeholder.jpg"
            )

            review_image_captions.append(caption)

    ### Save captions into dataset
    user_review_data[i]["image_captions"] = review_image_captions

print("ALL DONE!")

filename = 'augmented_user_review.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(user_review_data, f, indent=4)